### PR TITLE
Converted methods to functions. Refactored code.

### PR DESCRIPTION
**Pull request by cofonseca**
- Removed $obj, and rewrote its methods as traditional functions. I kept all variable names the same. 
- Changed Return to Write-Output as it's a bit more standard when it comes to PS toolmaking
- Changed Write-Host to Write-Error. Same as above.

I have no way of testing this, so I'd appreciate your help with testing!

### CODE REVIEW

**Comment by iamraghavs** [comment]
Good one @cofonseca . Will test it out and get back to you!

**Comment by iamraghavs** [comment]
Regarding `Write-Output` there is a discussion [here](https://github.com/PoshCode/PowerShellPracticeAndStyle/issues/46) where there seems to be a concensus around putting the variable on its own line. Comments?

**Comment by cofonseca** [comment]
@raghav710 that's a pretty interesting discussion. I personally prefer using Write-Output for a couple of reasons:

- It's clear that anything after Write-Output is actually output. By just leaving the variable by itself on a line, it's not always immediately obvious. Most IDEs will add syntax highlighting to Write-Output as well.
- Write-Output sort of fits nicely with the other output commands, such as Write-Error, Write-Verbose, etc. I feel that sticking to the Verb-Noun naming convention is a cleaner and more standard practice.

This is all my own personal opinion, but if you have any preference yourself, I'm happy to make the changes and go with whatever you decide on. This is your project, after all!

**Comment by iamraghavs** [comment]
@cofonseca I think we can let it be like this then for now as I too dont have any strong preferences. I am fine with the PR. will merge when I've tested it. Thanks!

**Comment by cofonseca** [comment]
Excellent, thanks! If it doesn't work for whatever reason just let me know - happy to make any changes where needed.

**Comment by iamraghavs** [comment]
Thanks for your contribution @cofonseca . I notice that the CreateDatabase and other calls are within the new_document_db_rest_client function. I think we could move them out and make the documentDBEndpointUri and documentDBMasterKey params to the whole file and remove the new_documentDB_rest_client method. Thoughts?

**Pull request merged**
